This package implements functionalities for time-optimal path
parameterization for object-transportation.

To simplify a contact, then parametrize a trajectory, run the
following script:
#+BEGIN_SRC sh
  transport.paper simplify-contact -c bigcup_bluenb\
		  -o bluenb -a denso_suction_cup2\
		  -T "[[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 23.5e-3], [0, 0, 0, 1]]"\
		  -r suctioncup1 -v

  python parametrize_trajectory.py -t suctioncup_traj5a\
	 -c bigskirt_squarewood2_a2e54d1ae4\
	 -o squarewood2 -a denso_suction_cup2\
	 -T "[[1, 0, 0, 0e-3], [0, -1, 0, 0], [0, 0, -1, 23.5e-3], [0, 0, 0, 1]]"\
	 -r suctioncup1 -l topp_fast_2 -v
#+END_SRC

To run a trajectory
#+BEGIN_SRC sh
  python run_trajectory.py -t suctioncup_traj5a_14ca6c4b6c
#+END_SRC

TO start the Denso hardware
#+BEGIN_SRC sh
  roslaunch ftsensorless hardware_interface.launch robot_ip:=192.168.0.11\
	    ftsensor_ip:=192.168.0.12 gripper_ip:=192.168.0.14\
	    has_gripper:=false

 roslaunch ftsensorless controllers.launch load_position_joint_controller:=true

#+END_SRC


* Note on testing

  need to activate environment ros, and run gazebo virtual environment for testing

  #+BEGIN_SRC sh
    # term 1
    workon ros
    roslaunch ftsensorless gazebo_interface.launch robot_urdf:=denso_robotiq_85_gripper_pin  
    # term 2
    workon ros
    roslaunch ftsensorless controllers.launch load_position_joint_controller:=true

    # then, in term 3, test by running
    pytest -v # or -x to 
  #+END_SRC
  
* bigcup w/out skirt with blue notebook experiment
  contact: bigcup_bluenb
  attached to bluenb

  #+BEGIN_SRC sh
    transport.paper simplify-contact -c bigcup_bluenb\
		    -o bluenb -a denso_suction_cup2\
		    -T "[[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 12.5e-3], [0, 0, 0, 1]]"\
		    -r suctioncup1 -v

    python parametrize_trajectory.py -c bigcup_bluenb_1608823082\
	   -o bluenb -a denso_suction_cup2\
	   -T "[[1, 0, 0, 0e-3], [0, -1, 0, 0], [0, 0, -1, 12.5e-3], [0, 0, 0, 1]]"\
	   -t suctioncup_traj5a\
	   -r suctioncup1 -l topp_fast_2  -v

    python run_trajectory.py -t suctioncup_traj5a_57c22f0413

  #+END_SRC
  
* quantitative experiment
  
  the EXPERIMENT to finish.

  #+BEGIN_SRC sh
  transport.paper pick-demo --scene "scenarios/exp1.scenario.yaml" -e 
  #+END_SRC
* robust experiment
  target:
  - 5 object/transform combinations

    See svg file `robust_exp_configurations.svg`

    1. Configuration 1: blue notebook, its long edge is parallel to the suction cup's X-AXIS.

       #+BEGIN_SRC sh
       -o bluenb -a denso_suction_cup2 -T "[[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 12.5e-3], [0, 0, 0, 1]]" \
       #+END_SRC

    2. Configuration 2: blue notebook, its short edge is parallel to the suction cup's X-AXIS.

       #+BEGIN_SRC sh
       -o bluenb -a denso_suction_cup2 -T "[[0, -1, 0, 0], [-1, 0, 0, 0], [0, 0, -1, 12.5e-3], [0, 0, 0, 1]]" \
       #+END_SRC

    3. 

       #+BEGIN_SRC sh
       -o bluenb -a denso_suction_cup2 -T "[[1, 0, 0, 20e-3], [0, -1, 0, 0], [0, 0, -1, 12.5e-3], [0, 0, 0, 1]]" \
       #+END_SRC
    
  - 5 trajectories
  - 3 different strategies
    - w_contact
    - w_contact (use -d to scale vel to 1.3 times faster)
    - w_contact_jerk
    - kin_only
    - kin_only (use -d to scale vel to 0.7 times faster)

  object/transform 1: bluenb at perpendicular
  #+BEGIN_SRC sh
    transport.paper robust-experiment -c bigcup_bluenb_1608823082 \
		    -o bluenb -a denso_suction_cup2 -T "[[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 12.5e-3], [0, 0, 0, 1]]" \
		    -t traj1 \
		    -S nil \
		    -d 1.0 -e -v
  #+END_SRC

  object/transform 1: bluenb at perpendicular
  #+BEGIN_SRC sh
    transport.paper robust-experiment -c bigcup_bluenb_1608823082 \
		    -o bluenb -a denso_suction_cup2 -T "[[0, -1, 0, 0], [-1, 0, 0, 0], [0, 0, -1, 12.5e-3], [0, 0, 0, 1]]" \
		    -t traj1 \
		    -S nil \
		    -d 1.0 -e -v
  #+END_SRC

